### ISSUE TITLE
Mispelled Words in English Version

### ISSUE THREAD

**Issue by xaviervalarino** [nkanaev/zen101#14]
Many of the stories in the English version have misspelled words and odd grammar that seem to indicate the use of an overly aggressive spell checker. For instance, I noticed that quite often the word _hue_ appears were the word _true_ should be.

I considered making corrections in a PR, but wonder if it would be easier to replace these koans with English translations that do not have these mistakes, instead of going through each story by hand.

**Comment by nkanaev** [comment]
if there's a version without mistakes, I'd be glad to accept it instead of the current one.
But the new one should have been checked as well.

As of the "hue" misspelling - thanks for noticing, it has been fixed.

**Comment by xaviervalarino** [comment]
I will see if I can schedule some time to go through each story and cross reference other version online.
