### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by sevillaarvin** [nkanaev/zen101#15]
Hello, the site is broken at the moment.

![image](https://user-images.githubusercontent.com/33614172/186000186-6d61ef1c-0420-45ac-82b6-2f5ece7305e7.png)

P.S. Love reading these!

**Comment by sevillaarvin** [comment]
Ah so only the custom domain is broken, I can access it via https://nkanaev.github.io/zen101/en/

**Comment by nkanaev** [comment]
i was changing the personal website repo/domain. sorry for the disruption.
the correct way to access is via github.io domain.
